create extension if not exists pgcrypto;

create table if not exists public.sales_leads (
  wa_id text primary key,
  display_name text,
  lead_stage text not null default 'NEW'
    check (lead_stage in ('NEW','DISCOVERY','QUALIFYING','INTERESTED','BOOKING','HUMAN_HANDOFF','WON','LOST','NURTURE')),
  product_interest text,
  company text,
  role text,
  budget text,
  timeline text,
  pain_point text,
  objection text,
  last_intent text,
  lead_score integer not null default 0 check (lead_score between 0 and 100),
  meeting_status text not null default 'not_requested',
  preferred_meeting_time text,
  human_handoff boolean not null default false,
  opted_out boolean not null default false,
  last_contact_at timestamptz,
  next_followup_at timestamptz,
  final_outcome text check (final_outcome is null or final_outcome in ('WON','LOST','NURTURE')),
  source text default 'whatsapp',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sales_messages (
  id uuid primary key default gen_random_uuid(),
  wa_id text not null references public.sales_leads(wa_id) on delete cascade,
  provider_message_id text unique,
  direction text not null check (direction in ('inbound','outbound')),
  message_text text,
  detected_intent text,
  lead_stage text,
  raw_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.sales_stage_history (
  id bigint generated by default as identity primary key,
  wa_id text not null references public.sales_leads(wa_id) on delete cascade,
  from_stage text,
  to_stage text not null,
  reason text,
  changed_by text not null default 'workflow',
  created_at timestamptz not null default now()
);

create table if not exists public.sales_followups (
  id uuid primary key default gen_random_uuid(),
  wa_id text not null references public.sales_leads(wa_id) on delete cascade,
  due_at timestamptz not null,
  status text not null default 'scheduled'
    check (status in ('scheduled','sent','cancelled','skipped','failed')),
  reason text,
  message_draft text,
  delivery_mode text,
  attempts integer not null default 0,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sales_handoffs (
  id uuid primary key default gen_random_uuid(),
  wa_id text not null references public.sales_leads(wa_id) on delete cascade,
  reason text,
  status text not null default 'open'
    check (status in ('open','accepted','resolved')),
  assigned_to text,
  opened_at timestamptz not null default now(),
  resolved_at timestamptz
);

create index if not exists sales_leads_stage_idx on public.sales_leads(lead_stage);
create index if not exists sales_leads_followup_idx on public.sales_leads(next_followup_at);
create index if not exists sales_messages_wa_created_idx on public.sales_messages(wa_id, created_at desc);
create index if not exists sales_followups_due_idx on public.sales_followups(status, due_at);
create index if not exists sales_handoffs_status_idx on public.sales_handoffs(status, opened_at);
